### ISSUE TITLE
add support for Buderus / Bosch heaters

### ISSUE THREAD

**Issue by moustic999** [patvdleer/nefit-client-python#5]
dear

Should it be possible to add the support of Bosch / Buderus flavour   ?
something similar already exist in https://github.com/robertklep/bosch-xmpp 
That would allow to have support in Home-assistant via ha-nefit.

there is another existing module https://github.com/stefanlaheij/ha-buderus which was using the internal http but is not compatible anymore with home-assistant.
this way of accessing the heating could also be supported in future ? that avoid to go to public XMPP servers an use the internal http api.

regards

**Comment by patvdleer** [comment]
Sorry for the late reply, I'll look into it but I will need help testing since I don't own one.

**Comment by patvdleer** [comment]
@moustic999 is it the IVT client what you need?
